services:
  dnsmasq-adblock:
    build: .
    container_name: dnsmasq-adblock
    restart: unless-stopped

    ports:
      - "${DNS_BIND_IP}:53:53/udp"
      - "${DNS_BIND_IP}:53:53/tcp"

    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf:ro,Z
      - ./config/upstream.conf:/etc/dnsmasq.d/upstream.conf:ro,Z
      - ./config/local.conf:/etc/dnsmasq.d/local.conf:ro,Z
      - ./config/blocklist-urls.txt:/etc/dnsmasq-adblock/blocklist-urls.txt:ro,Z
      - ./generated:/generated:Z
      - ./scripts:/scripts:ro,Z

    cap_add:
      - NET_ADMIN