services:
  dnsmasq-adblock:
    build:
      context: .
      args:
        - DNS_BIND_IP=${DNS_BIND_IP}
        - DNS_CACHE_SIZE=${DNS_CACHE_SIZE}
        - DNS_LISTEN_PORT=${DNS_LISTEN_PORT}
    image: dnsmasq-adblock:latest
    container_name: dnsmasq-adblock

    ports:
      - "${DNS_BIND_IP}:${DNS_LISTEN_PORT:-53}:53/udp"
      - "${DNS_BIND_IP}:${DNS_LISTEN_PORT:-53}:53/tcp"

    # volumes:
      # - ./config/dnsmasq.conf:/etc/dnsmasq.conf:rw,Z
      # - ./config/upstream.conf:/etc/dnsmasq.d/upstream.conf:ro,Z
      # - ./config/local.conf:/etc/dnsmasq.d/local.conf:ro,Z
      # - ./config/blocklist-urls.txt:/etc/dnsmasq.d/blocklist-urls.txt:ro,Z
      # - ./generated:/generated:Z
      # - ./scripts:/scripts:ro,Z

    cap_add:
      - NET_ADMIN