on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    name: Test dnsmasq-adblock
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout dnsmasq-adblock repository
        uses: actions/checkout@v4
      - name: make test script executable
        run: chmod +x ./scripts/test.sh
      - name: Run ./scripts/test.sh
        run: |
          bash ./scripts/test.sh
